name: laserod
channels:
  - conda-forge
dependencies:
  - python==3.7.2
  - orekit==9.2
  - jupyter
  - jupyterlab
  - requests # Used for making requests to the laser ranging data API
  - numpy
  - pandas
  - matplotlib
  - nodejs # For installing Jupyter lab extensions
  - pip:
    - spacetrack