name: laserod
channels:
  - plotly
  - conda-forge
dependencies:
  - python
  - orekit==12.0.1
  - jupyter
  - jupyterlab
  - requests # Used for making requests to the laser ranging data API
  - numpy
  - pandas
  - matplotlib
  - plotly
  - python-kaleido
  - psutil
  - pip
  - pip:
    - spacetrack