name: laserod
channels:
  - conda-forge
dependencies:
  - python
  - orekit
  - jupyter
  - jupyterlab
  - requests # Used for making requests to the laser ranging data API
  - numpy
  - pandas
  - matplotlib
  - nodejs # For installing Jupyter lab extensions
  - plotly
  - pip
  - pip:
    - spacetrack